version: '3.9'

networks:
  virus-network:
    name: virus-network
    driver: bridge

volumes:
  virus-redis-volume:
  virus-postgres-volume:

services:
  db:
    image: postgres:14.5-alpine
    container_name: virus-db
    restart: always
    ports: ["5010:5432"]
    environment:
      POSTGRES_DB: virus
      POSTGRES_USER: virus
      POSTGRES_PASSWORD: virus
      POSTGRES_PORT: 5000
    volumes:
      - virus-postgres-volume:/var/lib/postgresql/data
    networks:
      - virus-network